/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_dynamodb_all_tables_region: "ap-northeast-1",
  aws_dynamodb_table_schemas: [
    {
      tableName: "products-dev",
      region: "ap-northeast-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "ap-northeast-1:552062c8-cab4-4ded-829a-52363f1f24b7",
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: "ap-northeast-1_RQOdIsBC7",
  aws_user_pools_web_client_id: "lko5egc16mrmaebk6fe5htrq5",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_cloud_logic_custom: [
    {
      name: "reactApi",
      endpoint:
        "https://6cccy4u3bh.execute-api.ap-northeast-1.amazonaws.com/dev",
      region: "ap-northeast-1",
    },
    {
      name: "MyreactApi",
      endpoint: "http://18.180.74.254:8083",
    },
  ],
};

export default awsmobile;
